Watching for file changes with StatReloader
D:\FYP All data\Development\Backend\backend\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\FYP All data\Development\Backend\backend\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/authentication/profile/candidate/image/
Internal Server Error: /api/authentication/candidate/
Traceback (most recent call last):
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FYP All data\Development\Backend\authentication\views.py", line 189, in post
    user = authenticate(username=username, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/authentication/profile/candidate/image/
Internal Server Error: /api/authentication/register/
Traceback (most recent call last):
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE "auth_user"."username...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FYP All data\Development\Backend\authentication\views.py", line 164, in post
    if User.objects.filter(username=username).exists():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Zubair\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE "auth_user"."username...
                             ^

Watching for file changes with StatReloader
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
D:\FYP All data\Development\Backend\backend\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Watching for file changes with StatReloader
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/recruiter/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/completed/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/completed/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/chat/current-candidate/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/authentication/profile/candidate/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/publicposts/
Unauthorized: /api/job_posting/candidate/interview/completed/
Unauthorized: /api/chat/current-candidate/
Unauthorized: /api/job_posting/candidate/interview/incomplete/
Not Found: /api/authentication/profile/image/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/job_posting/candidate/applied-jobs/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
Unauthorized: /api/authentication/token/refresh/
